// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: fixedfunction.proto

package p4translation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPsecProtocolParams int32

const (
	IPsecProtocolParams_IPSEC_PROTOCOL_PARAMS_ESP IPsecProtocolParams = 0
)

// Enum value maps for IPsecProtocolParams.
var (
	IPsecProtocolParams_name = map[int32]string{
		0: "IPSEC_PROTOCOL_PARAMS_ESP",
	}
	IPsecProtocolParams_value = map[string]int32{
		"IPSEC_PROTOCOL_PARAMS_ESP": 0,
	}
)

func (x IPsecProtocolParams) Enum() *IPsecProtocolParams {
	p := new(IPsecProtocolParams)
	*p = x
	return p
}

func (x IPsecProtocolParams) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPsecProtocolParams) Descriptor() protoreflect.EnumDescriptor {
	return file_fixedfunction_proto_enumTypes[0].Descriptor()
}

func (IPsecProtocolParams) Type() protoreflect.EnumType {
	return &file_fixedfunction_proto_enumTypes[0]
}

func (x IPsecProtocolParams) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPsecProtocolParams.Descriptor instead.
func (IPsecProtocolParams) EnumDescriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{0}
}

type IPsecMode int32

const (
	IPsecMode_IPSEC_MODE_TRANSPORT IPsecMode = 0
	IPsecMode_IPSEC_MODE_TUNNEL    IPsecMode = 1
)

// Enum value maps for IPsecMode.
var (
	IPsecMode_name = map[int32]string{
		0: "IPSEC_MODE_TRANSPORT",
		1: "IPSEC_MODE_TUNNEL",
	}
	IPsecMode_value = map[string]int32{
		"IPSEC_MODE_TRANSPORT": 0,
		"IPSEC_MODE_TUNNEL":    1,
	}
)

func (x IPsecMode) Enum() *IPsecMode {
	p := new(IPsecMode)
	*p = x
	return p
}

func (x IPsecMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPsecMode) Descriptor() protoreflect.EnumDescriptor {
	return file_fixedfunction_proto_enumTypes[1].Descriptor()
}

func (IPsecMode) Type() protoreflect.EnumType {
	return &file_fixedfunction_proto_enumTypes[1]
}

func (x IPsecMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPsecMode.Descriptor instead.
func (IPsecMode) EnumDescriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{1}
}

type IPsecLifetimeAction int32

const (
	IPsecLifetimeAction_IPSEC_LIFETIME_ACTION_UNSET           IPsecLifetimeAction = 0
	IPsecLifetimeAction_IPSEC_LIFETIME_ACTION_TERMINATE_CLEAR IPsecLifetimeAction = 1
	IPsecLifetimeAction_IPSEC_LIFETIME_ACTION_TERMINATE_HOLD  IPsecLifetimeAction = 2
	IPsecLifetimeAction_IPSEC_LIFETIME_ACTION_REPLACE         IPsecLifetimeAction = 3
)

// Enum value maps for IPsecLifetimeAction.
var (
	IPsecLifetimeAction_name = map[int32]string{
		0: "IPSEC_LIFETIME_ACTION_UNSET",
		1: "IPSEC_LIFETIME_ACTION_TERMINATE_CLEAR",
		2: "IPSEC_LIFETIME_ACTION_TERMINATE_HOLD",
		3: "IPSEC_LIFETIME_ACTION_REPLACE",
	}
	IPsecLifetimeAction_value = map[string]int32{
		"IPSEC_LIFETIME_ACTION_UNSET":           0,
		"IPSEC_LIFETIME_ACTION_TERMINATE_CLEAR": 1,
		"IPSEC_LIFETIME_ACTION_TERMINATE_HOLD":  2,
		"IPSEC_LIFETIME_ACTION_REPLACE":         3,
	}
)

func (x IPsecLifetimeAction) Enum() *IPsecLifetimeAction {
	p := new(IPsecLifetimeAction)
	*p = x
	return p
}

func (x IPsecLifetimeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPsecLifetimeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_fixedfunction_proto_enumTypes[2].Descriptor()
}

func (IPsecLifetimeAction) Type() protoreflect.EnumType {
	return &file_fixedfunction_proto_enumTypes[2]
}

func (x IPsecLifetimeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPsecLifetimeAction.Descriptor instead.
func (IPsecLifetimeAction) EnumDescriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{2}
}

type IPsecSADBConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OffloadId            uint32               `protobuf:"varint,1,opt,name=offload_id,json=offloadId,proto3" json:"offload_id,omitempty"`
	Direction            bool                 `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"` // true = egress, false = ingress
	ReqId                uint64               `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Spi                  uint32               `protobuf:"varint,4,opt,name=spi,proto3" json:"spi,omitempty"`
	ExtSeqNum            bool                 `protobuf:"varint,5,opt,name=ext_seq_num,json=extSeqNum,proto3" json:"ext_seq_num,omitempty"`
	AntiReplayWindowSize uint32               `protobuf:"varint,6,opt,name=anti_replay_window_size,json=antiReplayWindowSize,proto3" json:"anti_replay_window_size,omitempty"`
	ProtocolParameters   IPsecProtocolParams  `protobuf:"varint,7,opt,name=protocol_parameters,json=protocolParameters,proto3,enum=p4translation.IPsecProtocolParams" json:"protocol_parameters,omitempty"`
	Mode                 IPsecMode            `protobuf:"varint,8,opt,name=mode,proto3,enum=p4translation.IPsecMode" json:"mode,omitempty"`
	EspPayload           *IPsecEspSa          `protobuf:"bytes,9,opt,name=esp_payload,json=espPayload,proto3" json:"esp_payload,omitempty"`
	SaHardLifetime       *IPsecSaHardLifetime `protobuf:"bytes,10,opt,name=sa_hard_lifetime,json=saHardLifetime,proto3" json:"sa_hard_lifetime,omitempty"`
	SaSoftLifetime       *IPsecSaSoftLifetime `protobuf:"bytes,11,opt,name=sa_soft_lifetime,json=saSoftLifetime,proto3" json:"sa_soft_lifetime,omitempty"`
}

func (x *IPsecSADBConfig) Reset() {
	*x = IPsecSADBConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fixedfunction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPsecSADBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPsecSADBConfig) ProtoMessage() {}

func (x *IPsecSADBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_fixedfunction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPsecSADBConfig.ProtoReflect.Descriptor instead.
func (*IPsecSADBConfig) Descriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{0}
}

func (x *IPsecSADBConfig) GetOffloadId() uint32 {
	if x != nil {
		return x.OffloadId
	}
	return 0
}

func (x *IPsecSADBConfig) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

func (x *IPsecSADBConfig) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *IPsecSADBConfig) GetSpi() uint32 {
	if x != nil {
		return x.Spi
	}
	return 0
}

func (x *IPsecSADBConfig) GetExtSeqNum() bool {
	if x != nil {
		return x.ExtSeqNum
	}
	return false
}

func (x *IPsecSADBConfig) GetAntiReplayWindowSize() uint32 {
	if x != nil {
		return x.AntiReplayWindowSize
	}
	return 0
}

func (x *IPsecSADBConfig) GetProtocolParameters() IPsecProtocolParams {
	if x != nil {
		return x.ProtocolParameters
	}
	return IPsecProtocolParams_IPSEC_PROTOCOL_PARAMS_ESP
}

func (x *IPsecSADBConfig) GetMode() IPsecMode {
	if x != nil {
		return x.Mode
	}
	return IPsecMode_IPSEC_MODE_TRANSPORT
}

func (x *IPsecSADBConfig) GetEspPayload() *IPsecEspSa {
	if x != nil {
		return x.EspPayload
	}
	return nil
}

func (x *IPsecSADBConfig) GetSaHardLifetime() *IPsecSaHardLifetime {
	if x != nil {
		return x.SaHardLifetime
	}
	return nil
}

func (x *IPsecSADBConfig) GetSaSoftLifetime() *IPsecSaSoftLifetime {
	if x != nil {
		return x.SaSoftLifetime
	}
	return nil
}

type IPsecEspSa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encryption *IPsecEncryption `protobuf:"bytes,1,opt,name=encryption,proto3" json:"encryption,omitempty"`
}

func (x *IPsecEspSa) Reset() {
	*x = IPsecEspSa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fixedfunction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPsecEspSa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPsecEspSa) ProtoMessage() {}

func (x *IPsecEspSa) ProtoReflect() protoreflect.Message {
	mi := &file_fixedfunction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPsecEspSa.ProtoReflect.Descriptor instead.
func (*IPsecEspSa) Descriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{1}
}

func (x *IPsecEspSa) GetEncryption() *IPsecEncryption {
	if x != nil {
		return x.Encryption
	}
	return nil
}

type IPsecEncryption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptionAlgorithm uint32 `protobuf:"varint,1,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	Key                 string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	KeyLen              uint32 `protobuf:"varint,3,opt,name=key_len,json=keyLen,proto3" json:"key_len,omitempty"`
}

func (x *IPsecEncryption) Reset() {
	*x = IPsecEncryption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fixedfunction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPsecEncryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPsecEncryption) ProtoMessage() {}

func (x *IPsecEncryption) ProtoReflect() protoreflect.Message {
	mi := &file_fixedfunction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPsecEncryption.ProtoReflect.Descriptor instead.
func (*IPsecEncryption) Descriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{2}
}

func (x *IPsecEncryption) GetEncryptionAlgorithm() uint32 {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return 0
}

func (x *IPsecEncryption) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IPsecEncryption) GetKeyLen() uint32 {
	if x != nil {
		return x.KeyLen
	}
	return 0
}

type IPsecSaHardLifetime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*IPsecSaHardLifetime_Time
	//	*IPsecSaHardLifetime_Bytes
	//	*IPsecSaHardLifetime_Packets
	//	*IPsecSaHardLifetime_Idle
	Value isIPsecSaHardLifetime_Value `protobuf_oneof:"value"`
}

func (x *IPsecSaHardLifetime) Reset() {
	*x = IPsecSaHardLifetime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fixedfunction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPsecSaHardLifetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPsecSaHardLifetime) ProtoMessage() {}

func (x *IPsecSaHardLifetime) ProtoReflect() protoreflect.Message {
	mi := &file_fixedfunction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPsecSaHardLifetime.ProtoReflect.Descriptor instead.
func (*IPsecSaHardLifetime) Descriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{3}
}

func (m *IPsecSaHardLifetime) GetValue() isIPsecSaHardLifetime_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *IPsecSaHardLifetime) GetTime() uint32 {
	if x, ok := x.GetValue().(*IPsecSaHardLifetime_Time); ok {
		return x.Time
	}
	return 0
}

func (x *IPsecSaHardLifetime) GetBytes() uint64 {
	if x, ok := x.GetValue().(*IPsecSaHardLifetime_Bytes); ok {
		return x.Bytes
	}
	return 0
}

func (x *IPsecSaHardLifetime) GetPackets() uint32 {
	if x, ok := x.GetValue().(*IPsecSaHardLifetime_Packets); ok {
		return x.Packets
	}
	return 0
}

func (x *IPsecSaHardLifetime) GetIdle() uint32 {
	if x, ok := x.GetValue().(*IPsecSaHardLifetime_Idle); ok {
		return x.Idle
	}
	return 0
}

type isIPsecSaHardLifetime_Value interface {
	isIPsecSaHardLifetime_Value()
}

type IPsecSaHardLifetime_Time struct {
	Time uint32 `protobuf:"varint,1,opt,name=time,proto3,oneof"`
}

type IPsecSaHardLifetime_Bytes struct {
	Bytes uint64 `protobuf:"varint,2,opt,name=bytes,proto3,oneof"`
}

type IPsecSaHardLifetime_Packets struct {
	Packets uint32 `protobuf:"varint,3,opt,name=packets,proto3,oneof"`
}

type IPsecSaHardLifetime_Idle struct {
	Idle uint32 `protobuf:"varint,4,opt,name=idle,proto3,oneof"`
}

func (*IPsecSaHardLifetime_Time) isIPsecSaHardLifetime_Value() {}

func (*IPsecSaHardLifetime_Bytes) isIPsecSaHardLifetime_Value() {}

func (*IPsecSaHardLifetime_Packets) isIPsecSaHardLifetime_Value() {}

func (*IPsecSaHardLifetime_Idle) isIPsecSaHardLifetime_Value() {}

type IPsecSaSoftLifetime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*IPsecSaSoftLifetime_Time
	//	*IPsecSaSoftLifetime_Bytes
	//	*IPsecSaSoftLifetime_Packets
	//	*IPsecSaSoftLifetime_Idle
	Value  isIPsecSaSoftLifetime_Value `protobuf_oneof:"value"`
	Action IPsecLifetimeAction         `protobuf:"varint,5,opt,name=action,proto3,enum=p4translation.IPsecLifetimeAction" json:"action,omitempty"`
}

func (x *IPsecSaSoftLifetime) Reset() {
	*x = IPsecSaSoftLifetime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fixedfunction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPsecSaSoftLifetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPsecSaSoftLifetime) ProtoMessage() {}

func (x *IPsecSaSoftLifetime) ProtoReflect() protoreflect.Message {
	mi := &file_fixedfunction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPsecSaSoftLifetime.ProtoReflect.Descriptor instead.
func (*IPsecSaSoftLifetime) Descriptor() ([]byte, []int) {
	return file_fixedfunction_proto_rawDescGZIP(), []int{4}
}

func (m *IPsecSaSoftLifetime) GetValue() isIPsecSaSoftLifetime_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *IPsecSaSoftLifetime) GetTime() uint32 {
	if x, ok := x.GetValue().(*IPsecSaSoftLifetime_Time); ok {
		return x.Time
	}
	return 0
}

func (x *IPsecSaSoftLifetime) GetBytes() uint64 {
	if x, ok := x.GetValue().(*IPsecSaSoftLifetime_Bytes); ok {
		return x.Bytes
	}
	return 0
}

func (x *IPsecSaSoftLifetime) GetPackets() uint32 {
	if x, ok := x.GetValue().(*IPsecSaSoftLifetime_Packets); ok {
		return x.Packets
	}
	return 0
}

func (x *IPsecSaSoftLifetime) GetIdle() uint32 {
	if x, ok := x.GetValue().(*IPsecSaSoftLifetime_Idle); ok {
		return x.Idle
	}
	return 0
}

func (x *IPsecSaSoftLifetime) GetAction() IPsecLifetimeAction {
	if x != nil {
		return x.Action
	}
	return IPsecLifetimeAction_IPSEC_LIFETIME_ACTION_UNSET
}

type isIPsecSaSoftLifetime_Value interface {
	isIPsecSaSoftLifetime_Value()
}

type IPsecSaSoftLifetime_Time struct {
	Time uint32 `protobuf:"varint,1,opt,name=time,proto3,oneof"`
}

type IPsecSaSoftLifetime_Bytes struct {
	Bytes uint64 `protobuf:"varint,2,opt,name=bytes,proto3,oneof"`
}

type IPsecSaSoftLifetime_Packets struct {
	Packets uint32 `protobuf:"varint,3,opt,name=packets,proto3,oneof"`
}

type IPsecSaSoftLifetime_Idle struct {
	Idle uint32 `protobuf:"varint,4,opt,name=idle,proto3,oneof"`
}

func (*IPsecSaSoftLifetime_Time) isIPsecSaSoftLifetime_Value() {}

func (*IPsecSaSoftLifetime_Bytes) isIPsecSaSoftLifetime_Value() {}

func (*IPsecSaSoftLifetime_Packets) isIPsecSaSoftLifetime_Value() {}

func (*IPsecSaSoftLifetime_Idle) isIPsecSaSoftLifetime_Value() {}

var File_fixedfunction_proto protoreflect.FileDescriptor

var file_fixedfunction_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x78, 0x65, 0x64, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa9, 0x04, 0x0a, 0x0f, 0x49, 0x50, 0x73, 0x65, 0x63, 0x53, 0x41,
	0x44, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x66, 0x66, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6f, 0x66,
	0x66, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x70, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x70, 0x69, 0x12, 0x1e,
	0x0a, 0x0b, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x74, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x35,
	0x0a, 0x17, 0x61, 0x6e, 0x74, 0x69, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x14, 0x61, 0x6e, 0x74, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x53, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x49, 0x50, 0x73, 0x65, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x34, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x50, 0x73, 0x65, 0x63, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x65, 0x73, 0x70, 0x5f,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x50,
	0x73, 0x65, 0x63, 0x45, 0x73, 0x70, 0x53, 0x61, 0x52, 0x0a, 0x65, 0x73, 0x70, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4c, 0x0a, 0x10, 0x73, 0x61, 0x5f, 0x68, 0x61, 0x72, 0x64, 0x5f,
	0x6c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49,
	0x50, 0x73, 0x65, 0x63, 0x53, 0x61, 0x48, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x52, 0x0e, 0x73, 0x61, 0x48, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x73, 0x61, 0x5f, 0x73, 0x6f, 0x66, 0x74, 0x5f, 0x6c, 0x69,
	0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70,
	0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x50, 0x73,
	0x65, 0x63, 0x53, 0x61, 0x53, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x52, 0x0e, 0x73, 0x61, 0x53, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x22, 0x4c, 0x0a, 0x0a, 0x49, 0x50, 0x73, 0x65, 0x63, 0x45, 0x73, 0x70, 0x53, 0x61, 0x12, 0x3e,
	0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x49, 0x50, 0x73, 0x65, 0x63, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6f,
	0x0a, 0x0f, 0x49, 0x50, 0x73, 0x65, 0x63, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x31, 0x0a, 0x14, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x13, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x4c, 0x65, 0x6e, 0x22,
	0x7e, 0x0a, 0x13, 0x49, 0x50, 0x73, 0x65, 0x63, 0x53, 0x61, 0x48, 0x61, 0x72, 0x64, 0x4c, 0x69,
	0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00,
	0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xba, 0x01, 0x0a, 0x13, 0x49, 0x50, 0x73, 0x65, 0x63, 0x53, 0x61, 0x53, 0x6f, 0x66, 0x74, 0x4c,
	0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x50, 0x73, 0x65, 0x63, 0x4c, 0x69, 0x66,
	0x65, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x34, 0x0a, 0x13,
	0x49, 0x50, 0x73, 0x65, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x19, 0x49, 0x50, 0x53, 0x45, 0x43, 0x5f, 0x50, 0x52, 0x4f,
	0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x5f, 0x45, 0x53, 0x50,
	0x10, 0x00, 0x2a, 0x3c, 0x0a, 0x09, 0x49, 0x50, 0x73, 0x65, 0x63, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x14, 0x49, 0x50, 0x53, 0x45, 0x43, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x52,
	0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x50, 0x53,
	0x45, 0x43, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x01,
	0x2a, 0xae, 0x01, 0x0a, 0x13, 0x49, 0x50, 0x73, 0x65, 0x63, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x1b, 0x49, 0x50, 0x53, 0x45,
	0x43, 0x5f, 0x4c, 0x49, 0x46, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x29, 0x0a, 0x25, 0x49, 0x50, 0x53,
	0x45, 0x43, 0x5f, 0x4c, 0x49, 0x46, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4c, 0x45,
	0x41, 0x52, 0x10, 0x01, 0x12, 0x28, 0x0a, 0x24, 0x49, 0x50, 0x53, 0x45, 0x43, 0x5f, 0x4c, 0x49,
	0x46, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x45,
	0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x5f, 0x48, 0x4f, 0x4c, 0x44, 0x10, 0x02, 0x12, 0x21,
	0x0a, 0x1d, 0x49, 0x50, 0x53, 0x45, 0x43, 0x5f, 0x4c, 0x49, 0x46, 0x45, 0x54, 0x49, 0x4d, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10,
	0x03, 0x42, 0x5e, 0x5a, 0x5c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x70, 0x69, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x70, 0x69, 0x2d, 0x65,
	0x76, 0x70, 0x6e, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x6c, 0x2d, 0x65, 0x32, 0x30, 0x30, 0x30, 0x2f, 0x70, 0x34, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x70, 0x34, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fixedfunction_proto_rawDescOnce sync.Once
	file_fixedfunction_proto_rawDescData = file_fixedfunction_proto_rawDesc
)

func file_fixedfunction_proto_rawDescGZIP() []byte {
	file_fixedfunction_proto_rawDescOnce.Do(func() {
		file_fixedfunction_proto_rawDescData = protoimpl.X.CompressGZIP(file_fixedfunction_proto_rawDescData)
	})
	return file_fixedfunction_proto_rawDescData
}

var file_fixedfunction_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fixedfunction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fixedfunction_proto_goTypes = []interface{}{
	(IPsecProtocolParams)(0),    // 0: p4translation.IPsecProtocolParams
	(IPsecMode)(0),              // 1: p4translation.IPsecMode
	(IPsecLifetimeAction)(0),    // 2: p4translation.IPsecLifetimeAction
	(*IPsecSADBConfig)(nil),     // 3: p4translation.IPsecSADBConfig
	(*IPsecEspSa)(nil),          // 4: p4translation.IPsecEspSa
	(*IPsecEncryption)(nil),     // 5: p4translation.IPsecEncryption
	(*IPsecSaHardLifetime)(nil), // 6: p4translation.IPsecSaHardLifetime
	(*IPsecSaSoftLifetime)(nil), // 7: p4translation.IPsecSaSoftLifetime
}
var file_fixedfunction_proto_depIdxs = []int32{
	0, // 0: p4translation.IPsecSADBConfig.protocol_parameters:type_name -> p4translation.IPsecProtocolParams
	1, // 1: p4translation.IPsecSADBConfig.mode:type_name -> p4translation.IPsecMode
	4, // 2: p4translation.IPsecSADBConfig.esp_payload:type_name -> p4translation.IPsecEspSa
	6, // 3: p4translation.IPsecSADBConfig.sa_hard_lifetime:type_name -> p4translation.IPsecSaHardLifetime
	7, // 4: p4translation.IPsecSADBConfig.sa_soft_lifetime:type_name -> p4translation.IPsecSaSoftLifetime
	5, // 5: p4translation.IPsecEspSa.encryption:type_name -> p4translation.IPsecEncryption
	2, // 6: p4translation.IPsecSaSoftLifetime.action:type_name -> p4translation.IPsecLifetimeAction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_fixedfunction_proto_init() }
func file_fixedfunction_proto_init() {
	if File_fixedfunction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fixedfunction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPsecSADBConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fixedfunction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPsecEspSa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fixedfunction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPsecEncryption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fixedfunction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPsecSaHardLifetime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fixedfunction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPsecSaSoftLifetime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fixedfunction_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*IPsecSaHardLifetime_Time)(nil),
		(*IPsecSaHardLifetime_Bytes)(nil),
		(*IPsecSaHardLifetime_Packets)(nil),
		(*IPsecSaHardLifetime_Idle)(nil),
	}
	file_fixedfunction_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*IPsecSaSoftLifetime_Time)(nil),
		(*IPsecSaSoftLifetime_Bytes)(nil),
		(*IPsecSaSoftLifetime_Packets)(nil),
		(*IPsecSaSoftLifetime_Idle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fixedfunction_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fixedfunction_proto_goTypes,
		DependencyIndexes: file_fixedfunction_proto_depIdxs,
		EnumInfos:         file_fixedfunction_proto_enumTypes,
		MessageInfos:      file_fixedfunction_proto_msgTypes,
	}.Build()
	File_fixedfunction_proto = out.File
	file_fixedfunction_proto_rawDesc = nil
	file_fixedfunction_proto_goTypes = nil
	file_fixedfunction_proto_depIdxs = nil
}
